config/routes.rb
Rails.application.routes.draw do
  scope "admin/manager" do
    resources :dashboards, only: %i(index)
    resources :users, only: %i(index new create edit update destroy)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  include ImageUploader[:image]
  include Discard::Model

  # 半角英数字, _, +, -, ., @を含む
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  # パスワード用正規表現
  PASSWORD_REGEX = /\A(?=.*[A-Za-z])(?=.*\d)(?=.*[!@#$%^&*_\-]).{6,}\z/.freeze
  # ふりがなは全角ひらがな
  KANA_REGEX = /\A[ぁ-んー－]+\z/.freeze
  # 郵便番号は7桁の数値
  POSTAL_CODE_REGEX = /\A\d{7}\z/.freeze
  # 電話番号は10桁または11桁の数値
  PHONE_NUMBER_REGEX = /\A\d{10,11}\z/.freeze

  with_options presence: true do                
    validates :email,            format: { with: EMAIL_REGEX, message: "は@マークを含む半角英数字で入力してください" }
    validates :name     
    validates :name_reading,     format: { with: KANA_REGEX, message: "はひらがなで入力してください" }
    validates :postal_code,      format: { with: POSTAL_CODE_REGEX, message: "はハイフンなしの7桁の数値で入力してください" }
    validates :prefecture
    validates :city             
    validates :address
    validates :phone_number,     format: { with: PHONE_NUMBER_REGEX, message: "はハイフンなしの10桁または11桁の数値で入力してください" }
    validates :birth_day
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_breadcrumbs

  private

  def add_breadcrumb(label, path = nil)
    @breadcrumbs << {
      label: label,
      path: path
    }
  end

  # パンくずリストの初期化
  def set_breadcrumbs
    @breadcrumbs = []
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i(edit update destroy)
  before_action :add_index_breadcrumb, only: %i(new edit)

  def index
    if params[:sort].present?
      if params[:sort] == "student"
        @users = User.where(student: true).order(:id).paginate(page: params[:page], per_page: 25)
      elsif params[:sort] == "parent"
        @users = User.where(parent: true).order(:id).paginate(page: params[:page], per_page: 25)
      end
    else
      @users = User.order(:id).paginate(page: params[:page], per_page: 25)
    end
  end

  def new
    @user = User.new
    @number = sprintf('%08d', rand(99999999))
    add_breadcrumb('新規会員登録')
  end

  def edit
    add_breadcrumb(@user.name, @todo)
    add_breadcrumb('会員情報')
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: "会員を登録しました."
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to action: :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to edit_user_path(@user), notice: "会員情報を更新しました。", status: :see_other
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to action: :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, notice: "会員をアーカイブしました。", status: :see_other
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :email,
      :image,
      :name,
      :name_reading,
      :phone_number,
      :number,
      :birth_day,
      :gender,
      :postal_code,
      :prefecture,
      :city,
      :address,
      :building,
      :stripe_customer_id,
      :status,
      :student,
      :parent
    )
  end

  def add_index_breadcrumb
    add_breadcrumb('会員一覧', users_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/index.html.erb
<div x-data="setup()" :class="{ 'dark': isDark }">
  <div class="min-h-screen flex flex-col flex-auto flex-shrink-0 antialiased bg-white dark:bg-gray-700 text-black dark:text-white">
    <%= render "layouts/shared/header" %>
    <%= render "layouts/shared/sidebar" %>
    <div class="h-full mt-16 mb-10">
      <div class="grid grid-cols-1 p-4 gap-4 mt-5">
        <h2 class="border-0 text-lg border-gray-400 border-l-4 border-b-4 p-2">各種フォーム</h2>
        <div>
          <button class="btn btn-xs sm:btn-sm md:btn-md lg:btn-lg btn-success text-white">入会フォーム(準備中)</button>
          <button class="btn btn-xs sm:btn-sm md:btn-md lg:btn-lg btn-warning text-white">体験レッスン申し込みフォーム(準備中)</button>
        </div>
      </div>
      <div class="grid grid-cols-1 p-4 gap-4 mt-5">
        <h2 class="border-0 text-lg border-gray-400 border-l-4 border-b-4 p-2">会員管理</h2>
        <div class="grid md:grid-cols-4 grid-cols-2 p-4 gap-4">
          <div class="group relative block h-full bg-white">
            <%= link_to users_path, class:"block rounded-lg border bg-white transition" do  %>
              <div class="bg-orange-100 p-4 sm:p-6">
                <h3 class="font-semibold text-gray-900 sm:text-lg">一覧</h3>
                <p class="mt-3 text-xs text-gray-700">スクールの会員一覧です</p>
              </div>
            <% end %>
          </div>
          <div class="group relative block h-full bg-white">
            <%= link_to users_path(sort: "student"), class:"block rounded-lg border bg-white transition" do  %>
              <div class="bg-orange-100 p-4 sm:p-6">
                <h3 class="font-semibold text-gray-900 sm:text-lg">在籍生徒</h3>
                <p class="mt-3 text-xs text-gray-700">レッスンに通う生徒の一覧です</p>
              </div>
            <% end %>
          </div>
          <div class="group relative block h-full bg-white">
            <%= link_to users_path(sort: "parent"), class:"block rounded-lg border bg-white transition" do  %>
              <div class="bg-orange-100 p-4 sm:p-6">
                <h3 class="font-semibold text-gray-900 sm:text-lg">保護者</h3>
                <p class="mt-3 text-xs text-gray-700">保護者様の一覧です</p>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="grid grid-cols-1 p-4 gap-4 mt-5">
        <h2 class="border-0 text-lg border-gray-400 border-l-4 border-b-4 p-2">拠点</h2>
        <div class="grid md:grid-cols-4 grid-cols-2 p-4 gap-4">
          <div class="group relative block h-full bg-white">
            <%= link_to "#", class:"block rounded-lg border bg-white transition" do %>
              <div class="bg-orange-100 p-4 sm:p-6">
                <h3 class="font-semibold text-gray-900 sm:text-lg">一覧</h3>
                <p class="mt-3 text-xs text-gray-700">校舎の一覧です</p>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="grid grid-cols-1 p-4 gap-4 mt-5">
        <h2 class="border-0 text-lg border-gray-400 border-l-4 border-b-4 p-2">スクール関連</h2>
        <div class="grid md:grid-cols-4 grid-cols-2 p-4 gap-4">
          <div class="group relative block h-full bg-white">
            <%= link_to "#", class:"block rounded-lg border bg-white transition" do %>
              <div class="bg-orange-100 p-4 sm:p-6">
                <h3 class="font-semibold text-gray-900 sm:text-lg">レッスン</h3>
                <p class="mt-3 text-xs text-gray-700">開講しているレッスンの一覧です</p>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= render "layouts/shared/footer" %>
</div>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My School Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>

    <!-- Font Awesomeの読み込み -->
    <script src="<%= ENV["FONT_AWESOME_KIT"]%>" crossorigin="anonymous"></script>
  </head>

  <body data-theme="lofi">
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.8.0/dist/alpine.min.js" defer></script>
    <script>
      const setup = () => {
        const getTheme = () => {
          if (window.localStorage.getItem('dark')) {
            return JSON.parse(window.localStorage.getItem('dark'))
          }
          return !!window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches
        }

        const setTheme = (value) => {
          window.localStorage.setItem('dark', value)
        }

        return {
          loading: true,
          isDark: getTheme(),
          toggleTheme() {
            this.isDark = !this.isDark
            setTheme(this.isDark)
          },
        }
      }
    </script>
  </body>
</html>

app/views/layouts/shared/_breadcrumbs.html.erb
<div class="max-w-lg text-sm breadcrumbs">
  <ul>
    <li>
      <%= link_to dashboards_path do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="w-4 h-4 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z"></path></svg>
        トップページ
      <% end %>
    </li> 
    <% @breadcrumbs.each do |breadcrumb| %>
      <% if breadcrumb[:path].blank? %>
        <li>
          <span class="inline-flex gap-2 items-center font-semibold">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="w-4 h-4 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z"></path></svg>
            <%= link_to breadcrumb[:label], breadcrumb[:path] %>
          </span>
        </li>
      <% else %>
        <li>
          <span class="inline-flex gap-2 items-center font-semibold">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="w-4 h-4 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z"></path></svg>
            <%= link_to breadcrumb[:label], breadcrumb[:path] %>
          </span>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/layouts/shared/_error_messages.html.erb
<% if flash[:errors].present? %>
  <% flash[:errors].each do |error| %>
    <p class="text-xs text-red-600 dark:text-white"><%= error %></p>
  <% end %>
<% end %>

app/views/layouts/shared/_footer.html.erb
<footer class="footer items-center p-4 bg-neutral text-neutral-content">
  <aside class="items-center grid-flow-col">
    <p>Copyright © 2023 MySchoolManager All right reserved</p>
  </aside> 
  <nav class="grid-flow-col gap-4 md:place-self-center md:justify-self-end items-center">
    <%= image_tag 'instagram.svg', width: "24", height: "24", class: "fill-current" %>
    <%= image_tag 'twitter.svg', width: "24", height: "24", class: "fill-current" %>
    <%= image_tag 'youtube.svg', width: "24", height: "24", class: "fill-current" %>
  </nav>
</footer>

app/views/layouts/shared/_header.html.erb
<div class="navbar bg-gray-700 dark:bg-gray-800 fixed">
  <div class="flex-1 ml-2">
    <%= link_to 'My School Manager', dashboards_path, class: "text-xs md:text-xl text-white block" %>
  </div>
  <div class="flex-none mr-2">
    <ul class="menu menu-horizontal px-1">
      <li>
        <button
          aria-hidden="true"
          @click="toggleTheme"
          class="group p-2 transition-colors duration-200 rounded-full shadow-md bg-green-200 hover:bg-green-200 dark:bg-gray-50 dark:hover:bg-gray-200 text-gray-900 focus:outline-none"
        >
          <svg
            x-show="isDark"
            width="24"
            height="24"
            class="fill-current text-gray-700 group-hover:text-gray-500 group-focus:text-gray-700 dark:text-gray-700 dark:group-hover:text-gray-500 dark:group-focus:text-gray-700"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke=""
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z"
            />
          </svg>
          <svg
            x-show="!isDark"
            width="24"
            height="24"
            class="fill-current text-gray-700 group-hover:text-gray-500 group-focus:text-gray-700 dark:text-gray-700 dark:group-hover:text-gray-500 dark:group-focus:text-gray-700"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke=""
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z"
            />
          </svg>
        </button>
      </li>
    </ul>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, class: "space-y-4 h-adr") do |form| %>
  <span class="p-country-name" style="display:none;">Japan</span>
  <%= render "layouts/shared/error_messages" %>
  <div>
    <%= form.label :name, class: "label" do %>
      <span class="text-base label-text dark:text-white">お名前</span>
    <% end %>
    <%= form.text_field :name, placeholder: "名前を入力", class: "w-full input input-bordered" %>
  </div>

  <div>
    <%= form.label :name_reading, class: "label" do %>
      <span class="text-base label-text dark:text-white">ふりがな</span>
    <% end %>
    <%= form.text_field :name_reading, placeholder: "ひらがなで入力", class: "w-full input input-bordered" %>
  </div>

  <div>
    <%= form.label :image_data, class: "label" do %>
      <span class="text-base label-text dark:text-white">プロフィール画像</span>
    <% end %>
    <%= form.hidden_field :image, value: user.cached_image_data %>
    <%= form.file_field :image, class: "w-full input input-bordered" %>
  </div>

  <div>
    <%= form.label :number, class: "label" do %>
      <span class="text-base label-text dark:text-white">会員番号 (※自動採番)</span>
    <% end %>
    <%= form.number_field :number, placeholder: "会員番号を入力", value: number, class: "w-full input input-bordered" %>
  </div>

  <div>
    <%= form.label :email, class: "label" do %>
      <span class="text-base label-text dark:text-white">メールアドレス</span>
    <% end %>
    <%= form.email_field :email, placeholder: "school@gmail.com", class: "w-full input input-bordered" %>
  </div>

  <div>
    <%= form.label :phone_number, class: "label" do %>
      <span class="text-base label-text dark:text-white">連絡先(電話番号)</span>
    <% end %>
    <%= form.text_field :phone_number, placeholder: "ハイフンなし・半角数字で入力", class: "w-full input input-bordered" %>
  </div>

  <div>
    <%= form.label :birth_day, class: "label" do %>
      <span class="text-base label-text dark:text-white">生年月日</span>
    <% end %>
    <%= form.date_field :birth_day, class: "w-full input input-bordered" %>
  </div>

  <div>
    <%= form.label :gender, class: "label" do %>
      <span class="text-base label-text dark:text-white">性別</span>
    <% end %>
    <%= form.select :gender, options_for_select(["男性", "女性"]), {}, class: "w-full input input-bordered" %>
  </div>

  <div>
    <%= form.label :postal_code, class: "label" do %>
      <span class="text-base label-text dark:text-white">郵便番号</span>
    <% end %>
    <%= form.number_field :postal_code, placeholder: "ハイフンなし・半角数字で入力", class: "p-postal-code w-full input input-bordered" %>
  </div>

  <div>
    <%= form.label :prefecture, class: "label" do %>
      <span class="text-base label-text dark:text-white">都道府県</span>
    <% end %>
    <%= form.text_field :prefecture, placeholder: "都道府県を入力", class: "p-region w-full input input-bordered" %>
  </div>

  <div>
    <%= form.label :city, class: "label" do %>
      <span class="text-base label-text dark:text-white">市町村</span>
    <% end %>
    <%= form.text_field :city, placeholder: "市町村を入力", class: "p-locality w-full input input-bordered" %>
  </div>

  <div>
    <%= form.label :address, class: "label" do %>
      <span class="text-base label-text dark:text-white">住所(番地)</span>
    <% end %>
    <%= form.text_field :address, placeholder: "住所(番地)を入力", class: "p-street-address w-full input input-bordered" %>
  </div>

  <div>
    <%= form.label :building, class: "label" do %>
      <span class="text-base label-text dark:text-white">建物・マンション名・部屋番号</span>
    <% end %>
    <%= form.text_field :building, placeholder: "建物・マンション名・部屋番号を入力", class: "p-extended-address w-full input input-bordered" %>
  </div>

  <div>
    <%= form.label :status, class: "label" do %>
      <span class="text-base label-text dark:text-white">ステータス</span>
    <% end %>
    <%= form.select :status, options_for_select([['アクティブ', 1], ['アーカイブ', 0]]), {}, class: "w-full input input-bordered" %>
  </div>

  <div>
    <%= form.label :student do %>
      <%= form.check_box :student, class: "input-checkbox" %>
      <span class="text-base label-text dark:text-white">生徒ラベル</span>
    <% end %>
  </div>

  <div>
    <%= form.label :parent do %>
      <%= form.check_box :parent, class: "input-checkbox" %>
      <span class="text-base label-text dark:text-white">保護者ラベル</span>
    <% end %>
  </div>

  <div>
    <%= form.button btn_msg, class: "btn btn-block text-white btn-success" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<tr class="border border-2">        
  <td class="border border-2">
    <div class="flex items-center gap-3">
      <div class="avatar">
        <div class="mask mask-squircle w-12 h-12">
          <% if !user.image_data.present? %>
            <%= image_tag user.image[:small].url %>
          <% else %>
            <%= image_tag "no-image.jpg", alt: "no-image", class: "w-5 h-5" %>
          <% end %>
        </div>
      </div>
      <%= link_to edit_user_path(user) do %>
        <div class="font-bold text-blue-600"><%= user.name %></div>
        <div class="text-sm opacity-50 dark:text-white"><%= user.name_reading %></div>
      <% end %>
    </div>
  </td>
  <td class="border border-2">
    <%= user.number %>
  </td>
  <td class="border border-2"><%= user.birth_day.strftime("%Y年%-m月%-d日") %></td>
</tr>

app/views/users/edit.html.erb
<div x-data="setup()" :class="{ 'dark': isDark }">
  <div class="min-h-screen flex flex-col flex-auto flex-shrink-0 antialiased bg-white dark:bg-gray-700 text-black dark:text-white">
    <%= render "layouts/shared/header" %>
    <%= render "layouts/shared/sidebar" %>
    <div class="h-full mt-16 mb-10">
      <div class="grid grid-cols-1 p-4 gap-4 mt-5">
        <%= render 'layouts/shared/breadcrumbs' %>
        <h2 class="border-0 text-lg border-gray-400 border-l-4 border-b-4 p-2"><%= @user.name%>さんの登録情報</h2>
        <div role="tablist" class="tabs tabs-bordered">
          <input type="radio" name="my_tabs_1" role="tab" class="tab text-xs md:text-base h-28 md:h-auto dark:text-white" aria-label="基本情報" checked />
          <div role="tabpanel" class="tab-content">
            <%= render "form", user: @user, number: @user.number, btn_msg: "更新" %>
          </div>

          <input type="radio" name="my_tabs_1" role="tab" class="tab text-xs md:text-base h-28 md:h-auto dark:text-white" aria-label="レッスン情報"  />
          <div role="tabpanel" class="tab-content">
            レッスン情報 準備中
          </div>

          <input type="radio" name="my_tabs_1" role="tab" class="tab text-xs md:text-base h-28 md:h-auto dark:text-white" aria-label="出席情報" />
          <div role="tabpanel" class="tab-content">
            出席情報 準備中
          </div>

          <input type="radio" name="my_tabs_1" role="tab" class="tab text-xs md:text-base h-28 md:h-auto dark:text-white" aria-label="決済情報"  />
          <div role="tabpanel" class="tab-content">
            決済情報 準備中
          </div>

          <input type="radio" name="my_tabs_1" role="tab" class="tab text-xs md:text-base h-28 md:h-auto dark:text-white" aria-label="準備中" />
          <div role="tabpanel" class="tab-content">
            準備中
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= render "layouts/shared/footer" %>
</div>
<%# 郵便番号自動表示ライブラリ %>
<script src="https://yubinbango.github.io/yubinbango/yubinbango.js" charset="UTF-8"></script>

app/views/users/index.html.erb
<div x-data="setup()" :class="{ 'dark': isDark }">
  <div class="min-h-screen flex flex-col flex-auto flex-shrink-0 antialiased bg-white dark:bg-gray-700 text-black dark:text-white">
    <%= render "layouts/shared/header" %>
    <%= render "layouts/shared/sidebar" %>
    <div class="h-full mt-16 mb-10">
      <div class="grid grid-cols-1 p-4 gap-4 mt-5">
        <%= render 'layouts/shared/breadcrumbs' %>
        <h2 class="border-0 text-lg border-gray-400 border-l-4 border-b-4 p-2">会員一覧</h2>
        <div class="overflow-x-auto">
          <table class="table border border-2">
            <caption class="caption-top">
              <div class="flex justify-between items-center mb-2">
                <div>
                  <%= link_to new_user_path, class: 'btn btn-primary' do %>
                    <p class="text-sm font-medium leading-none text-white">新規会員登録</p>
                  <% end %>
                </div>
              </div>
            </caption>
            <thead>
              <tr class="dark:text-white">
                <th class="border border-2">名前</th>
                <th class="border border-2">会員番号</th>
                <th class="border border-2">生年月日</th>
              </tr>
            </thead>
            <tbody class="border border-2"">
              <%= render partial: "user", collection: @users %>
            </tbody>
          </table>
          <div class="text-center my-4">
            <div role="navigation" aria-label="Pagination" class="px-3 py-2 mx-2 text-gray-700 no-underline bg-white rounded-lg dark:bg-gray-700 text-black dark:text-white">
              <div class="flickr_pagination">
                <div class="py-4">
                  <%= page_entries_info @users %>
                </div>
                <div class="py-4">
                  <%= will_paginate @users %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= render "layouts/shared/footer" %>
</div>  

app/views/users/new.html.erb
<div x-data="setup()" :class="{ 'dark': isDark }">
  <div class="min-h-screen flex flex-col flex-auto flex-shrink-0 antialiased bg-white dark:bg-gray-700 text-black dark:text-white">
    <%= render "layouts/shared/header" %>
    <%= render "layouts/shared/sidebar" %>
    <div class="h-full mt-16 mb-10">
      <div class="grid grid-cols-1 p-4 gap-4 mt-5">
        <%= render 'layouts/shared/breadcrumbs' %>
        <h2 class="border-0 text-lg border-gray-400 border-l-4 border-b-4 p-2">新規会員登録</h2>
        <%= render "form", user: @user, number: @number, btn_msg: "登録" %>
      </div>
    </div>
  </div>
  <%= render "layouts/shared/footer" %>
</div>
<%# 郵便番号自動表示ライブラリ %>
<script src="https://yubinbango.github.io/yubinbango/yubinbango.js" charset="UTF-8"></script>